/**
 * Winline Vietnam - Comprehensive Products Dataset
 * Official Website: https://winline.vn/
 */

const WINLINE_DATA = {
  company: {
    name: "Công ty TNHH Winline Việt Nam",
    taxId: "0106085370",
    taxDate: "15/01/2013 (Sở KH&ĐT TP Hà Nội)",
    hotline: "0949.761.893",
    techSupport: "1900 099 806",
    warranty: "0963.230.665",
    email: "Winlinevietnam@gmail.com",
    address: "Số 17, Ngõ 46 Quan Nhân, Phường Thanh Xuân, TP. Hà Nội",
    registeredOffice: "Số 7 BT6, Khu đô thị Pháp Vân - Tứ Hiệp, Phường Hoàng Liệt, Quận Hoàng Mai, TP. Hà Nội",
    workingHours: "Thứ 2 - Thứ 7: 8h00 - 17h30",
    slogan: "Chất lượng tạo niềm tin - Giải pháp thông gió & làm mát hàng đầu Việt Nam"
  },
  
  categories: [
    {
      id: "quat-dan-dung",
      name: "Quạt dân dụng",
      icon: "fa-fan",
      children: [
        { id: "quat-cay-dan-dung", name: "Quạt cây dân dụng", count: 18 },
        { id: "quat-treo-dan-dung", name: "Quạt treo tường gia đình", count: 14 },
        { id: "quat-tran", name: "Quạt trần trang trí & đảo trần", count: 22 },
        { id: "quat-ban-hop", name: "Quạt bàn & quạt hộp tản gió", count: 12 },
        { id: "quat-san-dan-dung", name: "Quạt sàn gia đình", count: 9 }
      ]
    },
    {
      id: "quat-cong-nghiep",
      name: "Quạt công nghiệp",
      icon: "fa-wind",
      highlight: true,
      children: [
        { id: "quat-cay-cong-nghiep", name: "Quạt cây công nghiệp", count: 28, active: true },
        { id: "quat-treo-cong-nghiep", name: "Quạt treo tường công nghiệp", count: 24 },
        { id: "quat-thong-gio-vuong", name: "Quạt thông gió vuông", count: 19 },
        { id: "quat-thong-gio-tron", name: "Quạt thông gió tròn", count: 15 },
        { id: "quat-ly-tam", name: "Quạt ly tâm", count: 16 },
        { id: "quat-huong-truc", name: "Quạt hướng trục", count: 14 },
        { id: "quat-hut-nuoc", name: "Quạt hút nước công nghiệp", count: 8 },
        { id: "quat-tran-hvls", name: "Quạt trần công nghiệp HVLS", count: 6 }
      ]
    },
    {
      id: "thong-gio-lam-mat",
      name: "Thông gió & làm mát",
      icon: "fa-temperature-low",
      children: [
        { id: "may-lam-mat-nha-xuong", name: "Máy làm mát nhà xưởng", count: 12 },
        { id: "tam-cooling-pad", name: "Tấm làm mát Cooling Pad", count: 8 },
        { id: "quat-hut-am-tran", name: "Quạt hút âm trần & nối ống", count: 17 },
        { id: "he-thong-loc-bui", name: "Hệ thống lọc bụi & cấp khí tươi", count: 11 }
      ]
    },
    {
      id: "phu-kien-khac",
      name: "Phụ kiện & khác",
      icon: "fa-cogs",
      children: [
        { id: "canh-quat-long", name: "Cánh quạt & Lồng quạt", count: 20 },
        { id: "dong-co-motor", name: "Động cơ Motor quạt", count: 15 },
        { id: "ong-gio-co-dan", name: "Ống gió mềm & Côn thu", count: 18 },
        { id: "tu-dien-dieu-khien", name: "Tủ điện điều khiển & Biến tần", count: 9 }
      ]
    }
  ],

  brands: [
    { id: "komasu", name: "Komasu", country: "Nhật Bản / VN", count: 12 },
    { id: "vinawind", name: "Vinawind", country: "Điện cơ Thống Nhất VN", count: 8 },
    { id: "deton", name: "Deton", country: "Chính hãng", count: 7 },
    { id: "dasin", name: "Dasin", country: "Đài Loan / VN", count: 6 },
    { id: "chinghai", name: "Chinghai", country: "Đài Loan", count: 15 },
    { id: "hatari", name: "Hatari", country: "Thái Lan", count: 9 },
    { id: "panasonic", name: "Panasonic", country: "Nhật Bản", count: 10 },
    { id: "nedfon", name: "Nedfon", country: "Chính hãng", count: 8 },
    { id: "khac", name: "Khác (iFan, Nanyoo)", country: "Quốc tế", count: 10 }
  ],

  products: [
    {
      id: "p1",
      code: "KM-750S",
      name: "Quạt Komasu KM-750S",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "komasu",
      brandName: "Komasu",
      power: 250,
      powerText: "250W",
      powerRange: "200-300",
      airflow: 15200,
      airflowText: "15.200 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 750,
      bladeText: "750mm",
      voltage: "220V / 50Hz",
      price: 2890000,
      oldPrice: 3250000,
      discount: 11,
      warranty: "24 tháng",
      rating: 5,
      reviewsCount: 38,
      stock: 45,
      isFeatured: true,
      isBestSeller: true,
      image: "assets/images/km750s.jpg",
      gallery: [
        "assets/images/km750s.jpg",
        "assets/images/km650s.jpg"
      ],
      description: "Quạt cây công nghiệp Komasu KM-750S sử dụng lồng mạ bóng sang trọng, cánh kim loại độ bền cao, lưu lượng gió cực mạnh 15.200 m³/h chuyên dùng cho nhà xưởng may, cơ khí, showroom, nhà hàng.",
      features: [
        "Động cơ dây đồng 100% chịu nhiệt cao, vận hành 24/7 êm ái",
        "Sải cánh 750mm đúc hợp kim nhôm định hình khí động học",
        "Thân cọc kim loại sơn tĩnh điện, chân đế gang đúc chống rung lắc",
        "Bảo hành chính hãng 24 tháng bởi Winline Việt Nam"
      ]
    },
    {
      id: "p2",
      code: "QD-650",
      name: "Quạt Vinawind QĐ-650",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "vinawind",
      brandName: "Vinawind",
      power: 220,
      powerText: "220W",
      powerRange: "200-300",
      airflow: 11000,
      airflowText: "11.000 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 650,
      bladeText: "650mm",
      voltage: "220V / 50Hz",
      price: 2150000,
      oldPrice: 2450000,
      discount: 12,
      warranty: "12 tháng",
      rating: 4.8,
      reviewsCount: 29,
      stock: 60,
      isFeatured: true,
      isBestSeller: true,
      image: "assets/images/qd650.jpg",
      gallery: [
        "assets/images/qd650.jpg"
      ],
      description: "Quạt cây công nghiệp Vinawind QĐ-650 chính hãng Điện cơ Thống Nhất, độ bền bỉ đã được khẳng định qua hàng chục năm. Giá thành cực kỳ tiết kiệm, phụ tùng dễ thay thế.",
      features: [
        "Cánh quạt 3 lá bản rộng tăng lưu lượng khí",
        "Núm vặn 3 tốc độ gió linh hoạt",
        "Góc xoay tản gió 90 độ làm mát diện rộng",
        "Hàng Việt Nam chất lượng cao"
      ]
    },
    {
      id: "p3",
      code: "DHF-750",
      name: "Quạt Deton DHF-750",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "deton",
      brandName: "Deton",
      power: 370,
      powerText: "370W",
      powerRange: "300-500",
      airflow: 20000,
      airflowText: "20.000 m³/h",
      airflowRange: "above-20000",
      bladeSize: 750,
      bladeText: "750mm",
      voltage: "220V / 50Hz",
      price: 3350000,
      oldPrice: 3750000,
      discount: 10,
      warranty: "36 tháng",
      rating: 5,
      reviewsCount: 42,
      stock: 35,
      isFeatured: true,
      isBestSeller: false,
      image: "assets/images/dhf750.jpg",
      gallery: [
        "assets/images/dhf750.jpg"
      ],
      description: "Quạt đứng công nghiệp Deton DHF-750 công suất khủng 370W, tạo lưu lượng gió đến 20.000 m³/h. Động cơ đúc tản nhiệt tốt, lồng nan dày dặn tiêu chuẩn công nghiệp nặng.",
      features: [
        "Công suất siêu mạnh 370W làm mát không gian rộng 100-150m²",
        "Bảo hành lên tới 36 tháng chính hãng",
        "Ổ bi NSK Nhật Bản tuổi thọ trên 10 năm",
        "Hệ thống tự ngắt bảo vệ quá nhiệt an toàn tuyệt đối"
      ]
    },
    {
      id: "p4",
      code: "KSF-3076",
      name: "Quạt Dasin KSF-3076",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "dasin",
      brandName: "Dasin",
      power: 260,
      powerText: "260W",
      powerRange: "200-300",
      airflow: 17000,
      airflowText: "17.000 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 760,
      bladeText: "760mm",
      voltage: "220V / 50Hz",
      price: 3050000,
      oldPrice: 3490000,
      discount: 13,
      warranty: "24 tháng",
      rating: 4.9,
      reviewsCount: 31,
      stock: 25,
      isFeatured: true,
      isBestSeller: true,
      image: "assets/images/ksf3076.jpg",
      gallery: [
        "assets/images/ksf3076.jpg"
      ],
      description: "Quạt công nghiệp 3 chân Dasin KSF-3076 Đài Loan với sải cánh 76cm hình tai voi bản lớn tạo áp lực gió sâu và xa đến 15m. Chân kiềng 3 chấu cực kỳ vững chắc.",
      features: [
        "Cánh quạt 3 lá nhôm đúc nguyên khối chống cong vênh",
        "Motor kín chống bụi bẩn xâm nhập, phù hợp môi trường bụi xưởng gỗ, xưởng đá",
        "Có cảm biến nhiệt TC tự ngắt khi motor đạt 120 độ C",
        "Dây cắm nguồn công nghiệp lõi đồng cao cấp"
      ]
    },
    {
      id: "p5",
      code: "KM-650S",
      name: "Quạt Komasu KM-650S",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "komasu",
      brandName: "Komasu",
      power: 200,
      powerText: "200W",
      powerRange: "200-300",
      airflow: 10000,
      airflowText: "10.000 m³/h",
      airflowRange: "5000-10000",
      bladeSize: 650,
      bladeText: "650mm",
      voltage: "220V / 50Hz",
      price: 1980000,
      oldPrice: 2290000,
      discount: 14,
      warranty: "24 tháng",
      rating: 4.8,
      reviewsCount: 45,
      stock: 50,
      isFeatured: false,
      isBestSeller: true,
      image: "assets/images/km650s.jpg",
      gallery: [
        "assets/images/km650s.jpg"
      ],
      description: "Quạt cây Komasu KM-650S với sải cánh 650mm là model bán chạy nhất cho các quán cà phê sân vườn, nhà hàng bia hơi, tiệc cưới và nhà xưởng vừa.",
      features: [
        "Lồng quạt mạ niken crom sáng bóng chống gỉ sét",
        "Độ ồn thấp dưới 68dB không gây khó chịu",
        "Điều chỉnh chiều cao linh hoạt từ 1.3m đến 1.7m",
        "Tiết kiệm điện năng vượt trội"
      ]
    },
    {
      id: "p6",
      code: "QD-750",
      name: "Quạt Vinawind QĐ-750",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "vinawind",
      brandName: "Vinawind",
      power: 300,
      powerText: "300W",
      powerRange: "300-500",
      airflow: 16000,
      airflowText: "16.000 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 750,
      bladeText: "750mm",
      voltage: "220V / 50Hz",
      price: 2650000,
      oldPrice: 2950000,
      discount: 10,
      warranty: "12 tháng",
      rating: 4.7,
      reviewsCount: 22,
      stock: 40,
      isFeatured: false,
      isBestSeller: false,
      image: "assets/images/qd750.jpg",
      gallery: [
        "assets/images/qd750.jpg"
      ],
      description: "Quạt cây công nghiệp Vinawind sải cánh 750mm công suất 300W, sức gió mạnh mẽ, bền bỉ, hàng Việt Nam uy tín hàng đầu.",
      features: [
        "Thân kim loại phủ sơn chống xước",
        "Cánh quạt hợp kim nhôm cân bằng động chính xác",
        "Động cơ dây đồng bọc gen cách điện chịu nhiệt",
        "Chân đế tròn vững chắc"
      ]
    },
    {
      id: "p7",
      code: "DHF-650",
      name: "Quạt Deton DHF-650",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "deton",
      brandName: "Deton",
      power: 220,
      powerText: "220W",
      powerRange: "200-300",
      airflow: 12500,
      airflowText: "12.500 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 650,
      bladeText: "650mm",
      voltage: "220V / 50Hz",
      price: 2450000,
      oldPrice: 2800000,
      discount: 13,
      warranty: "36 tháng",
      rating: 4.9,
      reviewsCount: 19,
      stock: 30,
      isFeatured: false,
      isBestSeller: false,
      image: "assets/images/dhf650.jpg",
      gallery: [
        "assets/images/dhf650.jpg"
      ],
      description: "Quạt cây Deton DHF-650 độ bền cao, bảo hành 3 năm, phù hợp với các công xưởng sản xuất liên tục nhiều ca trong ngày.",
      features: [
        "Sải cánh 650mm thiết kế khí động học giảm lực cản không khí",
        "Trục quay hợp kim tôi cứng chống mài mòn",
        "Chân quạt chữ thập có gắn đệm cao su giảm chấn",
        "Mức tiêu thụ điện thấp tối ưu chi phí vận hành"
      ]
    },
    {
      id: "p8",
      code: "KSF-2460",
      name: "Quạt Dasin KSF-2460",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "dasin",
      brandName: "Dasin",
      power: 160,
      powerText: "160W",
      powerRange: "under-200",
      airflow: 8000,
      airflowText: "8.000 m³/h",
      airflowRange: "5000-10000",
      bladeSize: 600,
      bladeText: "600mm",
      voltage: "220V / 50Hz",
      price: 1850000,
      oldPrice: 2150000,
      discount: 14,
      warranty: "24 tháng",
      rating: 4.8,
      reviewsCount: 26,
      stock: 28,
      isFeatured: false,
      isBestSeller: false,
      image: "assets/images/ksf2460.jpg",
      gallery: [
        "assets/images/ksf2460.jpg"
      ],
      description: "Quạt đứng Dasin KSF-2460 sải cánh 600mm 3 chân, motor kín chuyên dụng cho môi trường nhiều bụi và hơi ẩm.",
      features: [
        "Động cơ kín TC an toàn chuẩn chống bụi IP54",
        "Cánh nhôm 4 lá tản gió đều và êm",
        "Tuổi thọ vòng bi bạc đạn trên 60.000 giờ làm việc",
        "Bảo hành tận nơi trong nội thành Hà Nội"
      ]
    },
    {
      id: "p9",
      code: "KM-750T",
      name: "Quạt treo tường Komasu KM-750",
      category: "quat-cong-nghiep",
      subCategory: "quat-treo-cong-nghiep",
      brand: "komasu",
      brandName: "Komasu",
      power: 250,
      powerText: "250W",
      powerRange: "200-300",
      airflow: 15200,
      airflowText: "15.200 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 750,
      bladeText: "750mm",
      voltage: "220V / 50Hz",
      price: 2490000,
      oldPrice: 2850000,
      discount: 13,
      warranty: "24 tháng",
      rating: 4.9,
      reviewsCount: 35,
      stock: 40,
      isFeatured: true,
      isBestSeller: true,
      image: "assets/images/km-treo-750.jpg",
      gallery: [
        "assets/images/km-treo-750.jpg"
      ],
      description: "Quạt treo tường công nghiệp Komasu KM-750 tiết kiệm diện tích mặt sàn, gió thổi rộng và xa, giá đỡ gắn tường cực kỳ chắc chắn.",
      features: [
        "Sải cánh 750mm bằng hợp kim nhôm sáng bóng",
        "Túp năng cơ đảo chiều trái phải 90 độ mượt mà",
        "Giá treo bắt vít nở sắt chịu tải trọng trên 50kg an toàn tuyệt đối",
        "Công tắc dây kéo tiện lợi hoặc điều khiển hộp số"
      ]
    },
    {
      id: "p10",
      code: "KM-1380",
      name: "Quạt thông gió vuông Komasu KM-1380",
      category: "quat-cong-nghiep",
      subCategory: "quat-thong-gio-vuong",
      brand: "komasu",
      brandName: "Komasu",
      power: 1100,
      powerText: "1100W (1.1kW)",
      powerRange: "above-500",
      airflow: 44500,
      airflowText: "44.500 m³/h",
      airflowRange: "above-20000",
      bladeSize: 1250,
      bladeText: "1250mm",
      voltage: "380V / 220V",
      price: 3850000,
      oldPrice: 4300000,
      discount: 10,
      warranty: "18 tháng",
      rating: 5,
      reviewsCount: 54,
      stock: 30,
      isFeatured: true,
      isBestSeller: true,
      image: "assets/images/km-vuong-1380.jpg",
      gallery: [
        "assets/images/km-vuong-1380.jpg"
      ],
      description: "Quạt thông gió vuông composite/inox Komasu 1380x1380x400mm lưu lượng 44.500 m³/h chuyên kết hợp cùng Tấm làm mát Cooling Pad cho hệ thống làm mát áp suất âm nhà xưởng may, bao bì, trang trại chăn nuôi.",
      features: [
        "Khung tôn mạ kẽm độ mạ kẽm Z275 chống rỉ sét ngoài trời",
        "Lá chớp tự động đóng mở theo áp lực gió che mưa nắng",
        "Cánh inox 430 chống bám bụi và chống ăn mòn hóa chất",
        "Truyền động gián tiếp dây curoa giảm tiếng ồn, tăng mô-men xoắn"
      ]
    },
    {
      id: "p11",
      code: "KVF-1845",
      name: "Quạt thông gió vuông Dasin KVF-1845",
      category: "quat-cong-nghiep",
      subCategory: "quat-thong-gio-vuong",
      brand: "dasin",
      brandName: "Dasin",
      power: 135,
      powerText: "135W",
      powerRange: "under-200",
      airflow: 5400,
      airflowText: "5.400 m³/h",
      airflowRange: "5000-10000",
      bladeSize: 450,
      bladeText: "450mm",
      voltage: "220V / 50Hz",
      price: 1250000,
      oldPrice: 1450000,
      discount: 14,
      warranty: "24 tháng",
      rating: 4.8,
      reviewsCount: 17,
      stock: 45,
      isFeatured: false,
      isBestSeller: true,
      image: "assets/images/dasin-kvf1845.jpg",
      gallery: [
        "assets/images/dasin-kvf1845.jpg"
      ],
      description: "Quạt thông gió gắn tường Dasin KVF-1845 kích thước 56x56cm có công tắc đảo chiều 2 chiều (hút gió thải ra hoặc cấp khí tươi vào).",
      features: [
        "Hút & Thổi 2 chiều thông minh chỉ với 1 công tắc đảo chiều",
        "Có lưới bảo vệ 2 mặt chống côn trùng chuột bọ",
        "Motor 100% dây đồng nhúng vecni cách điện cấp F",
        "Ứng dụng cho phòng sơn, nhà bếp, kho hàng, phòng máy chủ"
      ]
    },
    {
      id: "p12",
      code: "FAG-1380",
      name: "Quạt thông gió Deton FAG-1380",
      category: "quat-cong-nghiep",
      subCategory: "quat-thong-gio-vuong",
      brand: "deton",
      brandName: "Deton",
      power: 1100,
      powerText: "1.1kW (380V)",
      powerRange: "above-500",
      airflow: 44000,
      airflowText: "44.000 m³/h",
      airflowRange: "above-20000",
      bladeSize: 1250,
      bladeText: "1250mm",
      voltage: "380V 3 pha",
      price: 4150000,
      oldPrice: 4600000,
      discount: 10,
      warranty: "36 tháng",
      rating: 5,
      reviewsCount: 39,
      stock: 22,
      isFeatured: false,
      isBestSeller: false,
      image: "assets/images/deton-fag1380.jpg",
      gallery: [
        "assets/images/deton-fag1380.jpg"
      ],
      description: "Quạt thông gió công nghiệp vuông Deton 1380x1380 chất lượng chuẩn Châu Âu, lá chớp mở bằng cơ cấu búa đẩy ly tâm thông minh bền bỉ.",
      features: [
        "Cơ cấu mở chớp bằng búa văng ly tâm trợ lực nhẹ nhàng",
        "Motor chuẩn IP55 chống nước mưa và bụi bẩn",
        "Bảo hành chính hãng 3 năm cho toàn bộ thân máy và động cơ",
        "Sản lượng gió ổn định, tiết kiệm điện năng cho nhà máy"
      ]
    },
    {
      id: "p13",
      code: "11-62-3.5A",
      name: "Quạt ly tâm hút khói cao áp Deton 11-62",
      category: "quat-cong-nghiep",
      subCategory: "quat-ly-tam",
      brand: "deton",
      brandName: "Deton",
      power: 2200,
      powerText: "2200W (2.2kW)",
      powerRange: "above-500",
      airflow: 6800,
      airflowText: "6.800 m³/h",
      airflowRange: "5000-10000",
      bladeSize: 350,
      bladeText: "350mm (Cánh ly tâm đa cánh)",
      voltage: "380V / 220V",
      price: 6950000,
      oldPrice: 7800000,
      discount: 11,
      warranty: "24 tháng",
      rating: 5,
      reviewsCount: 18,
      stock: 15,
      isFeatured: true,
      isBestSeller: false,
      image: "assets/images/deton-lytam.jpg",
      gallery: [
        "assets/images/deton-lytam.jpg"
      ],
      description: "Quạt ly tâm hút khói, hút khí thải lò hơi, nhà bếp công nghiệp, thông gió đường hầm áp suất tĩnh cao tới 1200Pa.",
      features: [
        "Cánh quạt ly tâm đa lá lồng sóc tạo cột áp đẩy rất xa",
        "Vỏ sò thép sơn tĩnh điện chống ăn mòn nhiệt và dầu mỡ",
        "Động cơ truyền động trực tiếp hoặc gián tiếp chịu nhiệt 280°C / 2 giờ",
        "Đáp ứng tiêu chuẩn PCCC QCVN 06:2022/BXD"
      ]
    },
    {
      id: "p14",
      code: "W18000",
      name: "Máy làm mát nhà xưởng Winline Air Cooler 18000",
      category: "thong-gio-lam-mat",
      subCategory: "may-lam-mat-nha-xuong",
      brand: "khac",
      brandName: "Winline Cool",
      power: 1100,
      powerText: "1100W",
      powerRange: "above-500",
      airflow: 18000,
      airflowText: "18.000 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 650,
      bladeText: "Cửa thổi đáy/thổi lên",
      voltage: "380V / 220V",
      price: 5600000,
      oldPrice: 6500000,
      discount: 14,
      warranty: "24 tháng",
      rating: 4.9,
      reviewsCount: 27,
      stock: 20,
      isFeatured: true,
      isBestSeller: true,
      image: "assets/images/air-cooler-18000.jpg",
      gallery: [
        "assets/images/air-cooler-18000.jpg"
      ],
      description: "Máy làm mát bay hơi công nghiệp Air Cooler lưu lượng 18.000 m³/h làm giảm nhiệt độ nhà xưởng từ 5°C - 8°C so với nhiệt độ ngoài trời, tiết kiệm 80% điện năng so với điều hòa.",
      features: [
        "Vỏ nhựa PP nguyên sinh dẻo dai, chống tia UV ngoài trời trên 10 năm",
        "Tấm Cooling pad chống rêu chất lượng cao 5090",
        "Hệ thống tự động xả cặn và bơm nước tuần hoàn thông minh",
        "Có điều khiển LCD gắn tường và remote điều khiển từ xa"
      ]
    },
    {
      id: "p15",
      code: "CP-1860",
      name: "Tấm làm mát Cooling Pad 1800x600x150mm chống rêu",
      category: "thong-gio-lam-mat",
      subCategory: "tam-cooling-pad",
      brand: "khac",
      brandName: "Cooling Pad",
      power: 0,
      powerText: "Không động cơ",
      powerRange: "under-200",
      airflow: 0,
      airflowText: "Hiệu suất 90%",
      airflowRange: "under-5000",
      bladeSize: 1800,
      bladeText: "1800x600x150mm",
      voltage: "N/A",
      price: 380000,
      oldPrice: 450000,
      discount: 15,
      warranty: "12 tháng",
      rating: 4.8,
      reviewsCount: 65,
      stock: 200,
      isFeatured: false,
      isBestSeller: true,
      image: "assets/images/cooling-pad.jpg",
      gallery: [
        "assets/images/cooling-pad.jpg"
      ],
      description: "Tấm làm mát giấy xenlulozo tự nhiên phủ lớp polyme chống rêu mốc màu đen một mặt, giữ nước tốt, giảm nhiệt độ không khí hiệu quả cho xưởng may và trang trại.",
      features: [
        "Chất liệu giấy kraft nguyên chất nhập khẩu từ Phần Lan",
        "Độ bền gấp 3 lần so với tấm làm mát thông thường không phủ chống rêu",
        "Khả năng hấp thụ nước và bốc hơi siêu tốc",
        "Không độc hại, thân thiện với môi trường"
      ]
    },
    {
      id: "p16",
      code: "F-60TDN",
      name: "Quạt trần 5 cánh Panasonic F-60TDN (Động cơ DC)",
      category: "quat-dan-dung",
      subCategory: "quat-tran",
      brand: "panasonic",
      brandName: "Panasonic",
      power: 37,
      powerText: "37W (Động cơ DC)",
      powerRange: "under-200",
      airflow: 14100,
      airflowText: "14.100 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 1500,
      bladeText: "1500mm (60 inch)",
      voltage: "220V / 50Hz",
      price: 4850000,
      oldPrice: 5500000,
      discount: 12,
      warranty: "12 tháng",
      rating: 5,
      reviewsCount: 88,
      stock: 40,
      isFeatured: true,
      isBestSeller: true,
      image: "assets/images/panasonic-tran.jpg",
      gallery: [
        "assets/images/panasonic-tran.jpg"
      ],
      description: "Quạt trần cao cấp Panasonic F-60TDN 5 cánh với công nghệ động cơ DC 1 chiều siêu êm và tiết kiệm điện tới 50%, trang bị 9 cấp độ gió cùng cảm biến nhiệt độ Econavi.",
      features: [
        "Cánh quạt 3D thiết kế khí động học sợi thủy tinh PPG siêu bền",
        "Chức năng tạo gió tự nhiên 1/f Yuragi tạo cảm giác dễ chịu mát mẻ",
        "Trang bị 3 cấp độ an toàn (Khóa cánh, Dây an toàn, Công tắc ngắt tự động)",
        "Màn hình LCD remote hiển thị rõ ràng"
      ]
    },
    {
      id: "p17",
      code: "IP22M1",
      name: "Quạt đứng Hatari IP22M1 Thái Lan",
      category: "quat-dan-dung",
      subCategory: "quat-cay-dan-dung",
      brand: "hatari",
      brandName: "Hatari",
      power: 197,
      powerText: "197W",
      powerRange: "under-200",
      airflow: 7200,
      airflowText: "7.200 m³/h",
      airflowRange: "5000-10000",
      bladeSize: 550,
      bladeText: "550mm (22 inch)",
      voltage: "220V / 50Hz",
      price: 2090000,
      oldPrice: 2390000,
      discount: 12,
      warranty: "36 tháng",
      rating: 4.9,
      reviewsCount: 47,
      stock: 35,
      isFeatured: false,
      isBestSeller: true,
      image: "assets/images/hatari-ip22m1.jpg",
      gallery: [
        "assets/images/hatari-ip22m1.jpg"
      ],
      description: "Quạt đứng bán công nghiệp Hatari IP22M1 nhập khẩu nguyên chiếc Thái Lan với chân đế tròn đúc siêu vững, 5 cánh tản gió êm ái.",
      features: [
        "Nhập khẩu chính ngạch nguyên chiếc từ Thái Lan",
        "Cầu chì nhiệt Thermal Fuse tự ngắt an toàn chống chập cháy",
        "Vòng bi bạc đạn siêu bền bảo hành motor 3 năm",
        "Tiêu chuẩn an toàn TIS 934-2558 Thái Lan"
      ]
    },
    {
      id: "p18",
      code: "DPT20-66B",
      name: "Quạt thông gió nối ống Nedfon DPT20-66B",
      category: "quat-cong-nghiep",
      subCategory: "quat-huong-truc",
      brand: "nedfon",
      brandName: "Nedfon",
      power: 185,
      powerText: "185W",
      powerRange: "under-200",
      airflow: 1500,
      airflowText: "1.500 m³/h",
      airflowRange: "under-5000",
      bladeSize: 200,
      bladeText: "Ống D200mm",
      voltage: "220V / 50Hz",
      price: 3450000,
      oldPrice: 3900000,
      discount: 11,
      warranty: "12 tháng",
      rating: 4.9,
      reviewsCount: 15,
      stock: 20,
      isFeatured: false,
      isBestSeller: false,
      image: "assets/images/nedfon-noi-ong.jpg",
      gallery: [
        "assets/images/nedfon-noi-ong.jpg"
      ],
      description: "Quạt hút nối ống thông gió âm trần Nedfon DPT20-66B độ ồn cực thấp chuyên dùng cho biệt thự, văn phòng cao cấp, khách sạn và bệnh viện.",
      features: [
        "Thiết kế 2 cấp tốc độ điều chỉnh linh hoạt",
        "Độ ồn siêu thấp chỉ 38dB hầu như không nghe thấy tiếng gió",
        "Áp suất tĩnh cao dễ dàng đẩy qua đường ống gió dài có nhiều góc cua",
        "Thân quạt bằng nhựa ABS chống cháy và chống va đập"
      ]
    },
    {
      id: "p19",
      code: "W9199",
      name: "Quạt công nghiệp Chinghai W9199",
      category: "quat-cong-nghiep",
      subCategory: "quat-cay-cong-nghiep",
      brand: "chinghai",
      brandName: "Chinghai",
      power: 280,
      powerText: "280W",
      powerRange: "200-300",
      airflow: 14800,
      airflowText: "14.800 m³/h",
      airflowRange: "10000-20000",
      bladeSize: 700,
      bladeText: "700mm",
      voltage: "220V / 50Hz",
      price: 2350000,
      oldPrice: 2650000,
      discount: 11,
      warranty: "12 tháng",
      rating: 4.8,
      reviewsCount: 30,
      stock: 35,
      isFeatured: false,
      isBestSeller: true,
      image: "assets/images/chinghai-w9199.jpg",
      gallery: [
        "assets/images/chinghai-w9199.jpg"
      ],
      description: "Quạt cây công nghiệp Chinghai W9199 Đài Loan sản xuất tại Việt Nam, độ hoàn thiện cao, hoạt động êm ái, cánh đỏ bắt mắt.",
      features: [
        "Cánh quạt nhựa dẻo cao cấp chống gãy khi va quệt",
        "Lồng quạt nan dầy sơn tĩnh điện chống rỉ sét",
        "Đế quạt nặng đúc nguyên khối chống đổ ngã",
        "Chuyển động tản gió góc 90 độ"
      ]
    },
    {
      id: "p20",
      code: "KHDB-2050",
      name: "Quạt sàn công nghiệp Dasin KHDB-2050",
      category: "quat-cong-nghiep",
      subCategory: "quat-san-dan-dung",
      brand: "dasin",
      brandName: "Dasin",
      power: 135,
      powerText: "135W",
      powerRange: "under-200",
      airflow: 6200,
      airflowText: "6.200 m³/h",
      airflowRange: "5000-10000",
      bladeSize: 500,
      bladeText: "500mm",
      voltage: "220V / 50Hz",
      price: 1450000,
      oldPrice: 1700000,
      discount: 15,
      warranty: "24 tháng",
      rating: 4.9,
      reviewsCount: 28,
      stock: 40,
      isFeatured: false,
      isBestSeller: false,
      image: "assets/images/dasin-san.jpg",
      gallery: [
        "assets/images/dasin-san.jpg"
      ],
      description: "Quạt chân quỳ sàn Dasin KHDB-2050 thổi sàn làm mát cho thợ cơ khí, sàn tập gym, sàn hội trường và khu vực lắp ráp điện tử.",
      features: [
        "Chân quỳ thép uốn chịu lực chống rung tuyệt đối",
        "Cánh quạt nhôm 3 lá tai voi cho sức gió cuộn tròn đi xa",
        "Điều chỉnh góc nghiêng thổi lên hoặc thổi ngang 180 độ",
        "Bánh xe di chuyển nhẹ nhàng trên sàn xưởng"
      ]
    }
  ],

  projects: [
    {
      title: "Nhà máy Samsung Electronics Thái Nguyên",
      category: "Nhà xưởng điện tử",
      scale: "45.000 m²",
      equipment: "120 quạt thông gió vuông Komasu 1380 + 350 tấm Cooling Pad",
      year: "2023",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=800&q=80"
    },
    {
      title: "Nhà máy May 10 Hưng Yên",
      category: "Dệt may công nghiệp",
      scale: "28.000 m²",
      equipment: "80 máy làm mát Air Cooler 18000 + 200 quạt cây Komasu KM-750",
      year: "2024",
      image: "https://images.unsplash.com/photo-1504917599217-d4dc5ebe6122?auto=format&fit=crop&w=800&q=80"
    },
    {
      title: "Tổ hợp Trang trại Bò sữa Vinamilk Ba Vì",
      category: "Trang trại chăn nuôi",
      scale: "50.000 con",
      equipment: "160 quạt hướng trục composite + Hệ thống phun sương áp lực",
      year: "2023",
      image: "https://images.unsplash.com/photo-1500595046743-cd271d694d30?auto=format&fit=crop&w=800&q=80"
    },
    {
      title: "Tòa nhà Keangnam Hanoi Landmark Tower",
      category: "Tòa nhà cao tầng",
      scale: "72 tầng",
      equipment: "Hệ thống quạt hút khói hành lang & quạt tăng áp cầu thang Nedfon",
      year: "2022",
      image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=800&q=80"
    }
  ]
};

if (typeof window !== "undefined") {
  window.WINLINE_DATA = WINLINE_DATA;
}
